const EDCD_FIELDS_BY_SHAPE: Record<string, string[]> = {
  "action-data-patching": ["levelOrCache", "targetRecord", "macro", "levelKind", "resultSlot"],
  "ability-check-branch": ["abilityOrAttribute", "adjustment", "attributeFlag", "successMacro", "failureMacro"],
  "ability-check-pick": ["abilityOrAttribute", "adjustment", "sourceSet", "attributeFlag", "unused"],
  battle: ["battleLow", "battleHigh", "soundOrReviveMacro", "message", "bootyMode"],
  "battle-macro": ["mode", "roundOrPercent", "repeatMode", "macroLow", "macroHigh"],
  "battle-variant": ["battleLow", "battleHigh", "branchOrSound", "message", "extra"],
  "boat-camp-state": ["mode", "statusValue", "branchModeOrBehavior", "targetOrValueA", "targetOrValueB"],
  "caste-selector": ["exactCaste", "casteGroup", "sourceSet", "unused", "unused"],
  "character-selector": ["selector", "value", "sourceSet", "unused", "unused"],
  "combat-monster-mutation": ["targetClass", "monsterId", "count", "replacementIcon", "traitorOverride"],
  condition: ["scope", "condition", "durationOrDelta", "sound", "unused"],
  "condition-branch": ["condition", "characterSelector", "unused", "trueMacro", "falseMacro"],
  "conditional-branch": ["testSelector", "branchModeOrValue", "falseBehavior", "trueTarget", "falseTarget"],
  choice: ["replyPolarity", "branchMode", "branchTarget", "promptA", "promptB"],
  "damage-heal": ["multiplier", "low", "high", "sound", "message"],
  "destroy-related": ["monsterId", "maxCount", "unused", "unused", "includeTraitorSide"],
  "dungeon-move": ["mode", "xOrDirection", "yOrDirection", "sound", "message"],
  "encounter-mutation": ["simpleEncounter", "oneBasedChoiceSlot", "unused", "unused", "unused"],
  "extended-door-codes": ["macro", "unused", "unused", "unused", "unused"],
  "false-true-branch": ["testA", "testB", "branchMode", "falseTarget", "trueTarget"],
  fatigue: ["mode", "unused", "percent", "unused", "unused"],
  fumble: ["message", "sound", "unused", "unused", "unused"],
  "force-branch": ["testA", "testB", "branchMode", "target", "slot"],
  gold: ["amount", "failureMarker", "unused", "unused", "unused"],
  "item-branch": ["item", "branchMode", "missingBehavior", "hasTarget", "missingTarget"],
  "item-charge-branch": ["item", "branchMode", "minimumCharges", "successTarget", "failureTarget"],
  "item-mutation": ["item", "maxMatches", "mode", "chargeDelta", "replacementItem"],
  "party-money-state": ["moneyType", "pickedOnly", "unused", "unused", "unused"],
  "party-state": ["amount", "scope", "unused", "unused", "unused"],
  "percent-branch": ["percent", "successBehavior", "branchMode", "target", "slot"],
  "position-shift": ["legacyLevel", "xShift", "yShift", "randomize", "unused"],
  "quest-value": ["quest", "delta", "branchMode", "threshold", "target"],
  "random-branch": ["branchMode", "rangeLow", "rangeHigh", "sound", "message"],
  "random-items": ["count", "itemLow", "itemHigh", "unused", "unused"],
  "random-region-mutation": ["level", "randomRegion", "percent", "battleLowOrKeep", "battleHighOrKeep"],
  "random-region-shape-mutation": ["level", "rect", "isDungeon", "percentDelta", "shapeMode"],
  "range-branch": ["testA", "testB", "falseBehavior", "branchMode", "target"],
  "render-mutation": ["landlook", "isDark", "targetLandLevel", "unused", "unused"],
  "restricted-shop": ["shop", "range1Low", "range1High", "range2Low", "range2High"],
  rout: ["monster1", "monster2", "monster3", "monster4", "monster5"],
  "save-restore-position": ["mode", "unused", "unused", "unused", "unused"],
  "selected-character-state": ["statSelector", "delta", "unused", "unused", "unused"],
  spawn: ["unused", "monster", "count", "sound", "traitorOverride"],
  "spell-cast": ["spell", "powerLevel", "saveAdjust", "forceAffect", "unused"],
  "spell-flags": ["spellcasting", "monstercasting", "spellcharging", "unused", "unused"],
  "spell-points": ["rollCount", "low", "high", "playSound", "message"],
  teleport: ["level", "x", "y", "sound", "message"],
  "tile-mutation": ["level", "xOrDungeonY", "yOrDungeonX", "tileValue", "isDungeon"],
  "time-mutation": ["mode", "day", "hour", "minute", "unused"],
  "timed-encounter-mutation": ["timedEncounter", "mode", "dayOrInterval", "hour", "minute"],
  "trigger-mutation": ["level", "singleTrigger", "percent", "rangeStartWithSign", "rangeEnd"],
  "unused-edcd-load": ["unused0", "unused1", "unused2", "unused3", "unused4"]
};

export function edcdFieldNamesForShape(shape: string | undefined) {
  if (!shape) return undefined;
  const normalized = shape.toLowerCase().replace(/\s*\/\s*/g, "-").replace(/\s+/g, "-");
  return EDCD_FIELDS_BY_SHAPE[normalized] ?? undefined;
}
