export const REALMZ_RACES = [
  "Human",
  "Shadow Elf",
  "Elf",
  "Orc",
  "Furfoot",
  "Gnome",
  "Dwarf",
  "Half Elf",
  "Half Orc",
  "Goblin",
  "Hobgoblin",
  "Kobold",
  "Vampire",
  "Lizard Man",
  "Brownie",
  "Pixie",
  "Leprechaun",
  "Demon",
  "Cathoon"
];

export const REALMZ_CASTES = [
  "Fighter",
  "Monk",
  "Crusader",
  "Archer",
  "Rogue",
  "Sorcerer",
  "Priest",
  "Enchanter",
  "Evoker",
  "Cardinal",
  "Cabalist",
  "Berzerker",
  "Bard",
  "Fencer",
  "Marksman",
  "Assassin",
  "Dabbler",
  "Battle Mage",
  "Warlock",
  "Minstrel"
];

export const SPELL_CASTER_CLASSES = ["Sorcerer", "Priest", "Enchanter", "Special", "Custom"];
export const SPELL_RESIST_CLASSES = ["Charm", "Heat", "Cold", "Electrical", "Chemical", "Mental", "Magical", "Special"];
export const SPELL_DAMAGE_TYPES = ["Charm", "Heat", "Cold", "Electrical", "Chemical", "Mental", "Magical", "Special", "Weapon", "Misc"];
export const SPELL_TARGET_TYPES = [
  "Multi Open Space",
  "Multi Target",
  "Single Target",
  "Fixed Size",
  "Area X Power",
  "Target Self",
  "Ray",
  "Target Party",
  "Single Open",
  "All Friendly",
  "All Enemies",
  "Special"
];

export const RACE_ATTRIBUTES = ["Brawn", "Knowledge", "Judgement", "Agility", "Vitality", "Luck"];
export const RESISTANCE_TYPES = ["Charm", "Heat", "Cold", "Electrical", "Chemical", "Mental", "Magical"];

export const ITEM_CATEGORY_LABELS = [
  "Small Blunt Weapons",
  "Medium Blunt Weapons",
  "Large Blunt Weapons",
  "Very Small Bladed Weapons",
  "Small Bladed Weapons",
  "Medium Bladed Weapons",
  "Large Bladed Weapons",
  "Very Large Bladed Weapons",
  "Staffs",
  "Spears",
  "Pole Arms",
  "Ninja Style Weapons",
  "Normal Bows",
  "Cross Bows",
  "Darts",
  "Flasks Of Oil",
  "Throwing Knife",
  "Whips",
  "Quiver",
  "Waist / Belt",
  "Neck / Necklace",
  "Caps",
  "Soft Helm",
  "Small Helm",
  "Large Helm",
  "Small Shield",
  "Med Shield",
  "Large Shield",
  "Bracers",
  "Cloth Gloves",
  "Leather Gloves",
  "Metal Gloves",
  "Cloak / Cape",
  "Robe",
  "Padded Armor",
  "Leather Armor",
  "Chain Armor",
  "Banded Armor",
  "Plate Armor",
  "Soft Boots",
  "Hard Boots",
  "Throwing Hammer",
  "Throwing Stars",
  "Misc. Blunt Weapon",
  "Misc. Bladed Weapon",
  "Misc. Large Weapon",
  "Misc. Missile Weapon",
  "Misc. Item",
  "Scroll Case",
  "Broach / Pin",
  "Ring",
  "Potion",
  "Misc. Magic Item",
  "Special Object",
  "Ion Stone",
  "Book",
  "Scroll"
];

export const RACE_DESCRIPTOR_LABELS = [
  "Short Race",
  "Elvish",
  "Half Breed",
  "Goblinoid",
  "Reptilian",
  "Nether Worldly",
  "Goodly Race",
  "Neutral Race",
  "Evil Race"
];

export const CONDITION_LABELS = [
  "Running",
  "Helpless",
  "Hindered",
  "Cursed",
  "Magic Aura",
  "Stupid",
  "Slow",
  "Shield From Hits",
  "Shield From Projectiles",
  "Poisoned",
  "Regenerating",
  "Fire Protection",
  "Cold Protection",
  "Electrical Protection",
  "Chemical Protection",
  "Mental Protection",
  "1st Level Spell Protection",
  "2nd Level Spell Protection",
  "3rd Level Spell Protection",
  "4th Level Spell Protection",
  "5th Level Spell Protection",
  "Strong",
  "Protection From Evil",
  "Speed",
  "Invisible",
  "Animated",
  "Stoned",
  "Blind",
  "Diseased",
  "Confused",
  "Reflect Spells",
  "Reflect Attacks",
  "Attack Bonus",
  "Absorb Spell Points",
  "Drain Spell Points",
  "Absorb Spell Points From Attacks",
  "Hinder Attack",
  "Hinder Defense",
  "Defense Bonus",
  "Silenced"
];
