pub(super) const CAPTURED_SCENARIO_SOURCE_FILES: &[&str] = &[
    "Custom 1 Music",
    "Custom 2 Music",
    "Custom 3 Music",
    "Data BD",
    "Data Caste",
    "Data CI",
    "Data CS",
    "Data Custom 1 BD",
    "Data Custom 2 BD",
    "Data Custom 3 BD",
    "Data DD",
    "Data DDD",
    "Data DES",
    "Data DL",
    "Data ED",
    "Data ED2",
    "Data ED3",
    "Data EDCD",
    "Data LD",
    "Data MD",
    "Data MD-1",
    "Data MD1",
    "Data MD2",
    "Data NI",
    "Data NI.rsrc",
    "Data OD",
    "Data RD",
    "Data RDD",
    "Data RI",
    "Data Race",
    "Data SD",
    "Data SD2",
    "Data Solids",
    "Data Spell",
    "Data Spell.rsrc",
    "Data TD",
    "Data TD2",
    "Data TD3",
    "Global",
    "Layout",
    "Scenario",
    "Scenario.rsrc",
];
