use super::{ActionDefinition, AuthoringLevel};

pub(super) struct ActionSeed {
    pub(super) opcode: i16,
    pub(super) label: &'static str,
    pub(super) category: &'static str,
    pub(super) description: &'static str,
    pub(super) form: Option<&'static str>,
}

const fn action(
    opcode: i16,
    label: &'static str,
    category: &'static str,
    description: &'static str,
    form: Option<&'static str>,
) -> ActionSeed {
    ActionSeed {
        opcode,
        label,
        category,
        description,
        form,
    }
}

pub(super) fn definitions() -> Vec<ActionDefinition> {
    ACTIONS
        .iter()
        .map(|seed| ActionDefinition {
            identity: format!("realmz.action.{}", seed.opcode),
            opcode: seed.opcode,
            label: seed.label.into(),
            category: seed.category.into(),
            description: seed.description.into(),
            storage: super::action_metadata::storage(seed),
            target_kind: super::target_rules::direct_target_kind(seed.opcode),
            form_id: seed.form.map(str::to_owned),
            selectable: true,
            authoring_level: if seed.opcode == 0 {
                AuthoringLevel::Empty
            } else if seed.opcode == 121 {
                AuthoringLevel::Advanced
            } else {
                AuthoringLevel::FirstClass
            },
            gosub_applicable: super::gosub_applicable(seed.opcode),
        })
        .collect()
}

pub(super) fn form_identity(opcode: i16) -> Option<&'static str> {
    ACTIONS
        .iter()
        .find(|seed| seed.opcode == opcode)
        .and_then(|seed| seed.form)
}

const ACTIONS: &[ActionSeed] = &[
    action(
        -23,
        "Change Dungeon Random Encounter Area",
        "Encounters",
        "Adjust a dungeon random encounter area.",
        Some("random-region-mutation"),
    ),
    action(
        -14,
        "Pick Opposite Characters",
        "Party",
        "Switch the selected character set to its opposite.",
        None,
    ),
    action(0, "Empty Step", "Advanced", "Leave this step unused.", None),
    action(
        1,
        "Show Message",
        "Dialogue",
        "Show a scenario message.",
        None,
    ),
    action(
        2,
        "Battle",
        "Encounters",
        "Start a battle or battle range.",
        Some("battle"),
    ),
    action(
        3,
        "Player Option",
        "Choices",
        "Ask the player a two-option question and route the result.",
        Some("choice"),
    ),
    action(
        4,
        "Start Simple Encounter",
        "Encounters",
        "Run a simple encounter.",
        None,
    ),
    action(
        5,
        "Start Complex Encounter",
        "Encounters",
        "Run a complex encounter.",
        None,
    ),
    action(6, "Open Shop", "Rewards", "Open a shop.", None),
    action(
        7,
        "Change Action Point Codes",
        "Logic",
        "Replace another Action Point or encounter result script with codes stored in an Extra Action Point.",
        Some("action-data-patching"),
    ),
    action(
        8,
        "Run Same-Map Action Point",
        "Extra Action Points",
        "Run another Action Point from the current map.",
        None,
    ),
    action(9, "Play Sound", "Media", "Play a sound effect.", None),
    action(
        10,
        "Give Treasure",
        "Rewards",
        "Give a treasure reward.",
        None,
    ),
    action(
        11,
        "Give Victory Points",
        "Rewards",
        "Give victory points to the party.",
        None,
    ),
    action(
        12,
        "Change Map Tile",
        "Travel",
        "Change a land or dungeon tile.",
        Some("tile-mutation"),
    ),
    action(
        13,
        "Change Action Point State",
        "Logic",
        "Enable, disable, or change an Action Point.",
        Some("trigger-mutation"),
    ),
    action(
        14,
        "Pick Characters",
        "Party",
        "Ask the player to pick party members for following steps.",
        None,
    ),
    action(
        15,
        "Change Picked Stamina",
        "Party",
        "Damage or heal the currently picked characters.",
        Some("damage-heal"),
    ),
    action(
        16,
        "Change Party Stamina",
        "Party",
        "Damage or heal every party member.",
        Some("damage-heal"),
    ),
    action(
        17,
        "Cast Spell",
        "Rules",
        "Cast a spell from this action.",
        Some("spell-cast"),
    ),
    action(
        18,
        "Force Spell",
        "Rules",
        "Force a spell effect.",
        Some("spell-cast"),
    ),
    action(
        19,
        "Show Random Message",
        "Dialogue",
        "Show a random message from a range.",
        Some("random-message"),
    ),
    action(
        20,
        "Move Party",
        "Travel",
        "Move the party to another level and cell.",
        Some("teleport"),
    ),
    action(
        21,
        "Branch On Item",
        "Items",
        "Branch depending on whether the party has an item.",
        Some("item-branch"),
    ),
    action(
        22,
        "Change Item",
        "Items",
        "Drop, charge, or replace item data.",
        Some("item-mutation"),
    ),
    action(
        23,
        "Change Random Encounter Area",
        "Encounters",
        "Adjust a land or dungeon random encounter area.",
        Some("random-region-mutation"),
    ),
    action(
        24,
        "Continue Steps",
        "Logic",
        "Keep evaluating following steps.",
        None,
    ),
    action(
        25,
        "Exit And Delete Action Point",
        "Logic",
        "Stop this script and delete or disable the current Action Point after it fires.",
        None,
    ),
    action(
        26,
        "Get Click",
        "Logic",
        "Wait for or capture a player click for following action behavior.",
        None,
    ),
    action(
        27,
        "Show Picture",
        "Media",
        "Show a picture resource.",
        None,
    ),
    action(
        28,
        "Redraw Screen",
        "Media",
        "Force Realmz to redraw the game screen.",
        None,
    ),
    action(
        29,
        "Show Map Reference",
        "Travel",
        "Use or reveal map-related data.",
        None,
    ),
    action(
        30,
        "Pick Characters By Check",
        "Party",
        "Pick characters by ability or attribute check.",
        Some("ability-check-pick"),
    ),
    action(
        31,
        "Branch On Check",
        "Logic",
        "Branch based on an ability or attribute check.",
        Some("ability-check-branch"),
    ),
    action(
        32,
        "Offer Temple",
        "Rewards",
        "Offer temple services using the ID value as the temple inflation rate.",
        None,
    ),
    action(
        33,
        "Take Gold Or Gems",
        "Rewards",
        "Ask the party to pay a specified amount of gold or gems, then branch on the result.",
        Some("gold"),
    ),
    action(
        34,
        "Break Encounter Loop",
        "Encounters",
        "Break out of an encounter loop; only meaningful inside encounter scripts.",
        None,
    ),
    action(
        35,
        "Eliminate Simple Encounter",
        "Encounters",
        "Remove one response choice from the currently running Simple Encounter.",
        None,
    ),
    action(
        36,
        "Capture Or Restore Equipment",
        "Items",
        "Capture or restore the party's equipment state.",
        None,
    ),
    action(
        37,
        "Enter / Exit Dungeon",
        "Travel",
        "Move the party between land and dungeon maps, then stop the script.",
        Some("dungeon-move"),
    ),
    action(
        38,
        "Branch On Item Possession",
        "Logic",
        "Route execution to another result or action.",
        Some("force-branch"),
    ),
    action(
        39,
        "Run Extra Action Point",
        "Extra Action Points",
        "Run an Extra Action Point.",
        None,
    ),
    action(
        40,
        "Branch On Party Condition",
        "Logic",
        "Branch based on party condition state.",
        Some("party-condition-branch"),
    ),
    action(
        41,
        "Change Encounter Choice",
        "Encounters",
        "Clear or change a simple encounter choice.",
        Some("encounter-mutation"),
    ),
    action(
        42,
        "Branch By Percent",
        "Logic",
        "Branch based on a percent roll.",
        Some("percent-branch"),
    ),
    action(
        43,
        "Change Condition",
        "Party",
        "Give or alter a party or character condition.",
        Some("condition"),
    ),
    action(
        44,
        "Eliminate Complex Encounter Choice",
        "Encounters",
        "Eliminate a branch from a complex encounter choice.",
        None,
    ),
    action(
        45,
        "Move Party Without Trigger",
        "Travel",
        "Move the party without firing the arrival trigger.",
        Some("teleport"),
    ),
    action(
        46,
        "Branch On Quest Flag",
        "Logic",
        "Route execution to another result or action.",
        Some("force-branch"),
    ),
    action(
        47,
        "Set Quest Flag",
        "Logic",
        "Set a quest flag value.",
        None,
    ),
    action(
        48,
        "Start Selective Battle",
        "Encounters",
        "Start a battle with optional message, sound, and treasure.",
        Some("selective-battle"),
    ),
    action(
        49,
        "Offer Banking",
        "Rewards",
        "Make the bank command available to the player.",
        None,
    ),
    action(
        50,
        "Pick Race Or Caste",
        "Party",
        "Pick characters by race, caste, class, or gender.",
        Some("race-caste-gender-selector"),
    ),
    action(
        51,
        "Change Shop",
        "Rewards",
        "Change shop inflation or stock.",
        Some("shop-mutation"),
    ),
    action(
        52,
        "Pick Characters By Miscellaneous Check",
        "Party",
        "Pick characters by movement, position, item, saves, or similar state.",
        Some("character-selector"),
    ),
    action(
        53,
        "Pick Caste",
        "Party",
        "Pick characters by caste.",
        Some("caste-selector"),
    ),
    action(
        54,
        "Change Timed Encounter",
        "Encounters",
        "Change a timed encounter schedule or state.",
        Some("timed-encounter-mutation"),
    ),
    action(
        55,
        "Branch On Picked Party",
        "Logic",
        "Branch based on whether characters are currently picked.",
        Some("picked-branch"),
    ),
    action(
        56,
        "Start Battle With Outcome",
        "Encounters",
        "Start a battle and route if the party flees.",
        Some("battle-outcome-branch"),
    ),
    action(
        57,
        "Change Land Look",
        "Travel",
        "Change the map's landlook or render state.",
        Some("render-mutation"),
    ),
    action(
        58,
        "Branch On Difficulty Level",
        "Logic",
        "Route execution to another result or action.",
        Some("force-branch"),
    ),
    action(
        59,
        "Branch On Tile ID",
        "Logic",
        "Route execution to another result or action.",
        Some("force-branch"),
    ),
    action(
        60,
        "Change Money State",
        "Rewards",
        "Change party money state.",
        Some("party-money-state"),
    ),
    action(
        61,
        "Shift Position",
        "Travel",
        "Shift the current party position.",
        Some("position-shift"),
    ),
    action(
        62,
        "Show Scrolling Text",
        "Dialogue",
        "Show a scrolling text scene.",
        None,
    ),
    action(
        63,
        "Change Time",
        "Logic",
        "Set or offset game time.",
        Some("time-mutation"),
    ),
    action(
        64,
        "Branch On Time",
        "Logic",
        "Branch based on the current game day and hour.",
        Some("game-time-branch"),
    ),
    action(
        65,
        "Give Random Items",
        "Items",
        "Give a random item from a range.",
        Some("random-items"),
    ),
    action(
        66,
        "Set Camping Ability",
        "Travel",
        "Control whether the party can camp.",
        None,
    ),
    action(
        67,
        "Branch On Item Charges",
        "Items",
        "Branch based on item charges.",
        Some("item-charge-branch"),
    ),
    action(
        68,
        "Change Fatigue",
        "Party",
        "Alter party or character fatigue.",
        Some("fatigue"),
    ),
    action(
        69,
        "Set Spell Flags",
        "Rules",
        "Set combat spellcasting flags.",
        Some("spell-flags"),
    ),
    action(
        70,
        "Save Or Restore Position",
        "Travel",
        "Save or restore party position.",
        Some("save-restore-position"),
    ),
    action(
        71,
        "Toggle Coordinate Display",
        "Travel",
        "Show or hide the coordinate display.",
        None,
    ),
    action(
        72,
        "Branch On Quest Range",
        "Logic",
        "Branch to a target based on a range or test.",
        Some("range-branch"),
    ),
    action(
        73,
        "Open Restricted Shop",
        "Rewards",
        "Open a restricted shop.",
        Some("restricted-shop"),
    ),
    action(
        74,
        "Change Spell Points",
        "Rules",
        "Alter spell points.",
        Some("spell-points"),
    ),
    action(
        75,
        "Branch On Spell Points",
        "Logic",
        "Branch to a target based on a range or test.",
        Some("range-branch"),
    ),
    action(
        76,
        "Set Quest Value",
        "Logic",
        "Write a quest value.",
        Some("quest-value"),
    ),
    action(
        77,
        "Branch On Quest Value",
        "Logic",
        "Branch on a quest value.",
        Some("false-true-branch"),
    ),
    action(
        78,
        "Branch On Tile Parameters",
        "Logic",
        "Branch to one result for false and another for true.",
        Some("false-true-branch"),
    ),
    action(
        81,
        "Branch On Character Condition",
        "Logic",
        "Branch to Extra Action Points based on condition state.",
        Some("condition-branch"),
    ),
    action(
        82,
        "Turn Cleric Turning Off",
        "Rules",
        "Disable cleric turning behavior.",
        None,
    ),
    action(
        83,
        "Turn Cleric Turning On",
        "Rules",
        "Enable cleric turning behavior.",
        None,
    ),
    action(
        84,
        "Legacy Registration Check",
        "Logic",
        "Run the retained legacy scenario registration gate.",
        None,
    ),
    action(
        85,
        "Branch Randomly",
        "Logic",
        "Branch to a random target in a range.",
        Some("random-branch"),
    ),
    action(
        86,
        "Branch On Miscellaneous Party State",
        "Logic",
        "Branch based on party, race, caste, gender, boat, camp, or level tests.",
        Some("misc-conditional-branch"),
    ),
    action(
        87,
        "Branch On Special Character Present",
        "Logic",
        "Branch based on conditional tests.",
        Some("conditional-branch"),
    ),
    action(
        88,
        "Drop Special Character",
        "Party",
        "Remove a special character from the party.",
        None,
    ),
    action(
        89,
        "Add Special Character",
        "Party",
        "Add a special character to the party.",
        None,
    ),
    action(
        90,
        "Change Party State",
        "Party",
        "Alter victory or experience-style party state.",
        Some("party-state"),
    ),
    action(
        91,
        "Drop All Equipment",
        "Items",
        "Drop all party equipment.",
        None,
    ),
    action(
        92,
        "Change Random Area Shape",
        "Encounters",
        "Change a random encounter area's percent and shape.",
        Some("random-region-shape-mutation"),
    ),
    action(
        93,
        "Turn Compass On",
        "Travel",
        "Enable the compass display.",
        None,
    ),
    action(
        94,
        "Turn Compass Off",
        "Travel",
        "Disable the compass display.",
        None,
    ),
    action(
        95,
        "Change Look Direction",
        "Travel",
        "Force the party to face a direction.",
        None,
    ),
    action(
        96,
        "Force 3D Dungeon View",
        "Travel",
        "Force the party to use the 3D view while in dungeons.",
        None,
    ),
    action(
        97,
        "Allow Full Map",
        "Travel",
        "Allow full-map viewing in dungeons; this action has no map-number argument.",
        None,
    ),
    action(
        98,
        "Require Registration",
        "Logic",
        "Run a legacy registration requirement check.",
        None,
    ),
    action(
        99,
        "Get Scenario Registration",
        "Logic",
        "Run the legacy scenario registration gate.",
        None,
    ),
    action(
        100,
        "End Battle",
        "Encounters",
        "End the current battle.",
        None,
    ),
    action(
        101,
        "Back Up Party",
        "Travel",
        "Move the party back one square opposite the direction they entered from.",
        None,
    ),
    action(
        102,
        "Level Up Picked Characters",
        "Party",
        "Level up the currently picked characters.",
        None,
    ),
    action(
        103,
        "Change Boat Or Camp",
        "Travel",
        "Change boat or camp state.",
        Some("boat-camp-state"),
    ),
    action(
        104,
        "Set Random Battle Availability",
        "Encounters",
        "Allow or disable mundane random-rectangle battles.",
        None,
    ),
    action(
        105,
        "Suspend Or Activate Allies",
        "Party",
        "Suspend or activate allies.",
        None,
    ),
    action(
        106,
        "Change Darkness",
        "Travel",
        "Set outdoor darkness state.",
        Some("dark-level-state"),
    ),
    action(
        107,
        "Start Improved Selective Battle",
        "Encounters",
        "Start an improved selective battle and route if the party flees.",
        Some("improved-selective-battle"),
    ),
    action(
        108,
        "Change Selected Character",
        "Party",
        "Alter selected-character combat or stat fields.",
        Some("selected-character-state"),
    ),
    action(
        111,
        "Return From Extra Action Point",
        "Extra Action Points",
        "Return from an Extra Action Point.",
        None,
    ),
    action(
        112,
        "Pop Script Stack",
        "Extra Action Points",
        "Pop script stack state.",
        None,
    ),
    action(
        119,
        "Revive NPC After Combat",
        "Encounters",
        "Revive an NPC after combat.",
        None,
    ),
    action(
        120,
        "Change Combat Monster",
        "Encounters",
        "Alter combat monster id, count, or icon state.",
        Some("combat-monster-mutation"),
    ),
    action(
        121,
        "De-animate Lower Undead",
        "Encounters",
        "Combat-macro action retained as advanced authoring outside its proven context.",
        Some("unused-edcd-load"),
    ),
    action(
        122,
        "Show Fumble Result",
        "Encounters",
        "Show combat fumble message or sound behavior.",
        Some("fumble"),
    ),
    action(
        123,
        "Rout Monsters",
        "Encounters",
        "Cause matching active combat monsters to rout.",
        Some("rout"),
    ),
    action(
        124,
        "Spawn Monsters",
        "Encounters",
        "Spawn combat monsters.",
        Some("spawn"),
    ),
    action(
        125,
        "Destroy Related Monsters",
        "Encounters",
        "Destroy related combat monsters.",
        Some("destroy-related"),
    ),
    action(
        126,
        "Run Battle Action",
        "Encounters",
        "Run battle action behavior.",
        Some("battle-macro"),
    ),
    action(
        127,
        "Continue If Monster Present",
        "Encounters",
        "Continue monster or battle macro behavior if a matching monster is present.",
        None,
    ),
];
