use super::RegistrationInput;

pub(super) struct Evidence {
    scenario: &'static str,
    first: Option<&'static str>,
    second: Option<&'static str>,
    name: &'static str,
    serial: i32,
    pub code: &'static str,
    pub identity: &'static str,
    pub label: &'static str,
    pub source: &'static str,
}

pub(super) fn matching(
    input: &RegistrationInput,
    serial: i32,
) -> impl Iterator<Item = &'static Evidence> {
    EVIDENCE.iter().filter(move |entry| {
        entry.scenario == input.scenario_name
            && entry.name == input.registration_name
            && entry.serial == serial
            && entry.first.is_none_or(|value| value == input.segment1)
            && entry.second.is_none_or(|value| value == input.segment2)
    })
}

// Exact recorded vectors from Providence 56ac232c registrationCodes.ts. These are evidence, not generated codes.
const EVIDENCE: &[Evidence] = &[
    Evidence {
        scenario: "Prelude to Pestilence",
        first: Some("Macdom"),
        second: Some("Norman Baites"),
        name: "RABREAUS",
        serial: 9140886,
        code: "25470888",
        identity: "officialMacEvidence",
        label: "Official Fantasoft Mac code",
        source: "Official Fantasoft MacOS registration form supplied by user.",
    },
    Evidence {
        scenario: "Assault on Giant Mountain",
        first: Some("MacMade"),
        second: Some("System 6.0.1"),
        name: "RABREAUS",
        serial: 9140886,
        code: "58371333",
        identity: "officialMacEvidence",
        label: "Official Fantasoft Mac code",
        source: "Official Fantasoft MacOS registration form supplied by user.",
    },
    Evidence {
        scenario: "Castle in the Clouds",
        first: Some("Yah Doc"),
        second: Some("Metal is our friend"),
        name: "RABREAUS",
        serial: 9140886,
        code: "26279812",
        identity: "officialMacEvidence",
        label: "Official Fantasoft Mac code",
        source: "Official Fantasoft MacOS registration form supplied by user.",
    },
    Evidence {
        scenario: "Destroy the Necronomicon",
        first: Some("Ian Bobein"),
        second: Some("Banana Fo Fanna"),
        name: "RABREAUS",
        serial: 9140886,
        code: "5013448",
        identity: "officialMacEvidence",
        label: "Official Fantasoft Mac code",
        source: "Official Fantasoft MacOS registration form supplied by user.",
    },
    Evidence {
        scenario: "White Dragon",
        first: Some("Tiny Worms"),
        second: Some("Mystic Rainbow"),
        name: "RABREAUS",
        serial: 9140886,
        code: "7476219",
        identity: "officialMacEvidence",
        label: "Official Fantasoft Mac code",
        source: "Official Fantasoft MacOS registration form supplied by user.",
    },
    Evidence {
        scenario: "Grilochs Revenge",
        first: Some("Very Aggresive"),
        second: Some("Stocks Rock"),
        name: "RABREAUS",
        serial: 9140886,
        code: "8731175",
        identity: "officialMacEvidence",
        label: "Official Fantasoft Mac code",
        source: "Official Fantasoft MacOS registration form supplied by user.",
    },
    Evidence {
        scenario: "Trouble in the Sword Lands",
        first: Some("Avast Matey!"),
        second: Some("Holy 28 Toes Batman"),
        name: "RABREAUS",
        serial: 9140886,
        code: "52358362",
        identity: "officialMacEvidence",
        label: "Official Fantasoft Mac code",
        source: "Official Fantasoft MacOS registration form supplied by user.",
    },
    Evidence {
        scenario: "Mithril Vault",
        first: Some("Vrap Attack!"),
        second: Some("Aquahaulic"),
        name: "RABREAUS",
        serial: 9140886,
        code: "3247949",
        identity: "officialMacEvidence",
        label: "Official Fantasoft Mac code",
        source: "Official Fantasoft MacOS registration form supplied by user.",
    },
    Evidence {
        scenario: "Twin Sands of Time",
        first: Some(""),
        second: Some(""),
        name: "RABREAUS",
        serial: 9140886,
        code: "42454079",
        identity: "officialMacEvidence",
        label: "Official Fantasoft Mac code",
        source: "Official Fantasoft MacOS registration form supplied by user.",
    },
    Evidence {
        scenario: "War in the Sword Lands",
        first: None,
        second: None,
        name: "RABREAUS",
        serial: 9140886,
        code: "24767635",
        identity: "officialMacEvidence",
        label: "Official Fantasoft Mac code",
        source: "Official Fantasoft MacOS registration form supplied by user.",
    },
    Evidence {
        scenario: "Half Truth",
        first: None,
        second: None,
        name: "RABREAUS",
        serial: 9140886,
        code: "31841033",
        identity: "officialMacEvidence",
        label: "Official Fantasoft Mac code",
        source: "Official Fantasoft MacOS registration form supplied by user.",
    },
    Evidence {
        scenario: "Wrath of the Mind Lords",
        first: Some("p38beta"),
        second: Some("p38delta"),
        name: "RABREAUS",
        serial: 9140886,
        code: "11993502",
        identity: "officialMacEvidence",
        label: "Official Fantasoft Mac code",
        source: "Official Fantasoft MacOS registration form supplied by user.",
    },
    Evidence {
        scenario: "Wrath of the Mind Lords",
        first: Some("p38beta"),
        second: Some("p38delta"),
        name: "SAMUEL",
        serial: 9140886,
        code: "268585916",
        identity: "reportedEvidence",
        label: "Reported external vector",
        source: "User-supplied Divinity Coder 7.0.9 screenshot and Mac runtime acceptance test for Wrath of the Mind Lords.",
    },
    Evidence {
        scenario: "Prelude to Pestilence",
        first: Some("Macdom"),
        second: Some("Norman Baites"),
        name: "RABREAUS",
        serial: 9140886,
        code: "1905660",
        identity: "officialWindowsEvidence",
        label: "Official Fantasoft Windows code",
        source: "Official Fantasoft Windows registration form supplied by user.",
    },
    Evidence {
        scenario: "Assault on Giant Mountain",
        first: Some("MacMade"),
        second: Some("System 6.0.1"),
        name: "RABREAUS",
        serial: 9140886,
        code: "1840485",
        identity: "officialWindowsEvidence",
        label: "Official Fantasoft Windows code",
        source: "Official Fantasoft Windows registration form supplied by user.",
    },
    Evidence {
        scenario: "Castle in the Clouds",
        first: Some("Yah Doc"),
        second: Some("Metal is our friend"),
        name: "RABREAUS",
        serial: 9140886,
        code: "1239074",
        identity: "officialWindowsEvidence",
        label: "Official Fantasoft Windows code",
        source: "Official Fantasoft Windows registration form supplied by user.",
    },
    Evidence {
        scenario: "Destroy the Necronomicon",
        first: Some("Ian Bobein"),
        second: Some("Banana Fo Fanna"),
        name: "RABREAUS",
        serial: 9140886,
        code: "202458",
        identity: "officialWindowsEvidence",
        label: "Official Fantasoft Windows code",
        source: "Official Fantasoft Windows registration form supplied by user.",
    },
    Evidence {
        scenario: "White Dragon",
        first: Some("Tiny Worms"),
        second: Some("Mystic Rainbow"),
        name: "RABREAUS",
        serial: 9140886,
        code: "204146",
        identity: "officialWindowsEvidence",
        label: "Official Fantasoft Windows code",
        source: "Official Fantasoft Windows registration form supplied by user.",
    },
    Evidence {
        scenario: "Grilochs Revenge",
        first: Some("Very Aggresive"),
        second: Some("Stocks Rock"),
        name: "RABREAUS",
        serial: 9140886,
        code: "460806",
        identity: "officialWindowsEvidence",
        label: "Official Fantasoft Windows code",
        source: "Official Fantasoft Windows registration form supplied by user.",
    },
    Evidence {
        scenario: "Trouble in the Sword Lands",
        first: Some("Avast Matey!"),
        second: Some("Holy 28 Toes Batman"),
        name: "RABREAUS",
        serial: 9140886,
        code: "1032019",
        identity: "officialWindowsEvidence",
        label: "Official Fantasoft Windows code",
        source: "Official Fantasoft Windows registration form supplied by user.",
    },
    Evidence {
        scenario: "Mithril Vault",
        first: Some("Vrap Attack!"),
        second: Some("Aquahaulic"),
        name: "RABREAUS",
        serial: 9140886,
        code: "109146",
        identity: "officialWindowsEvidence",
        label: "Official Fantasoft Windows code",
        source: "Official Fantasoft Windows registration form supplied by user.",
    },
    Evidence {
        scenario: "Twin Sands of Time",
        first: Some(""),
        second: Some(""),
        name: "RABREAUS",
        serial: 9140886,
        code: "1653401",
        identity: "officialWindowsEvidence",
        label: "Official Fantasoft Windows code",
        source: "Official Fantasoft Windows registration form supplied by user.",
    },
    Evidence {
        scenario: "War in the Sword Lands",
        first: None,
        second: None,
        name: "RABREAUS",
        serial: 9140886,
        code: "621043",
        identity: "officialWindowsEvidence",
        label: "Official Fantasoft Windows code",
        source: "Official Fantasoft Windows registration form supplied by user.",
    },
    Evidence {
        scenario: "Half Truth",
        first: None,
        second: None,
        name: "RABREAUS",
        serial: 9140886,
        code: "964355",
        identity: "officialWindowsEvidence",
        label: "Official Fantasoft Windows code",
        source: "Official Fantasoft Windows registration form supplied by user.",
    },
    Evidence {
        scenario: "Prelude to Pestilence",
        first: Some("Macdom"),
        second: Some("Norman Baites"),
        name: "JONESC",
        serial: 9515615,
        code: "1398120",
        identity: "officialMacEvidence",
        label: "Official Fantasoft Mac code",
        source: "Official Fantasoft MacOS registration form supplied by user.",
    },
    Evidence {
        scenario: "Assault on Giant Mountain",
        first: Some("MacMade"),
        second: Some("System 6.0.1"),
        name: "JONESC",
        serial: 9515615,
        code: "3204672",
        identity: "officialMacEvidence",
        label: "Official Fantasoft Mac code",
        source: "Official Fantasoft MacOS registration form supplied by user.",
    },
    Evidence {
        scenario: "Castle In The Clouds",
        first: Some("Yah Doc"),
        second: Some("Metal is our friend"),
        name: "JONESC",
        serial: 9515615,
        code: "1442844",
        identity: "officialMacEvidence",
        label: "Official Fantasoft Mac code",
        source: "Official Fantasoft MacOS registration form supplied by user.",
    },
    Evidence {
        scenario: "Destroy The Necronomicon",
        first: Some("Ian Bobein"),
        second: Some("Banana Fo Fanna"),
        name: "JONESC",
        serial: 9515615,
        code: "276995",
        identity: "officialMacEvidence",
        label: "Official Fantasoft Mac code",
        source: "Official Fantasoft MacOS registration form supplied by user.",
    },
    Evidence {
        scenario: "White Dragon",
        first: Some("Tiny Worms"),
        second: Some("Mystic Rainbow"),
        name: "JONESC",
        serial: 9515615,
        code: "412608",
        identity: "officialMacEvidence",
        label: "Official Fantasoft Mac code",
        source: "Official Fantasoft MacOS registration form supplied by user.",
    },
    Evidence {
        scenario: "Griloch's Revenge",
        first: Some("Very Aggresive"),
        second: Some("Stocks Rock"),
        name: "JONESC",
        serial: 9515615,
        code: "481007",
        identity: "officialMacEvidence",
        label: "Official Fantasoft Mac code",
        source: "Official Fantasoft MacOS registration form supplied by user.",
    },
    Evidence {
        scenario: "War in the Sword Lands",
        first: None,
        second: None,
        name: "AMBERK",
        serial: 13706024,
        code: "933071",
        identity: "reportedEvidence",
        label: "Reported external vector",
        source: "User-supplied War in the Sword Lands code with Realmz registration code 7995820 and verification code 410.",
    },
];
