pub(super) const LEGACY_SNAPSHOT_FORMAT_VERSION: u32 = 1;
pub(super) const PACKAGE_BOOTSTRAP_SNAPSHOT_FORMAT_VERSION: u32 = 2;
pub(super) const MAP_INPUT_SNAPSHOT_FORMAT_VERSION: u32 = 3;
pub(super) const ASSET_CATALOG_SNAPSHOT_FORMAT_VERSION: u32 = 4;
pub(super) const EXTRA_CODE_SNAPSHOT_FORMAT_VERSION: u32 = 5;
pub(super) const RULE_CATALOG_SNAPSHOT_FORMAT_VERSION: u32 = 6;
pub(super) const APPLICATION_CONTRACT_SNAPSHOT_FORMAT_VERSION: u32 = 7;
pub(super) const RULE_NAME_CATALOG_SNAPSHOT_FORMAT_VERSION: u32 = 8;
pub(super) const STANDARD_ITEM_CATALOG_SNAPSHOT_FORMAT_VERSION: u32 = 9;
pub(super) const SCENARIO_ITEM_CATALOG_SNAPSHOT_FORMAT_VERSION: u32 = 10;
pub(super) const EXTRA_ACTION_POINT_CATALOG_SNAPSHOT_FORMAT_VERSION: u32 = 12;
pub(super) const BATTLE_CATALOG_SNAPSHOT_FORMAT_VERSION: u32 = 14;
pub(super) const ROGUE_ENCOUNTER_CATALOG_SNAPSHOT_FORMAT_VERSION: u32 = 16;
pub(super) const TIMED_ENCOUNTER_CATALOG_SNAPSHOT_FORMAT_VERSION: u32 = 17;
pub(super) const PRE_SPELL_CATALOG_SNAPSHOT_FORMAT_VERSION: u32 = 18;
pub(super) const NAMED_SPELL_CATALOG_SNAPSHOT_FORMAT_VERSION: u32 = 20;
pub(super) const TREASURE_CATALOG_SNAPSHOT_FORMAT_VERSION: u32 = 22;
pub(super) const SHOP_CATALOG_SNAPSHOT_FORMAT_VERSION: u32 = 23;
pub(super) const OPTION_LABEL_CATALOG_SNAPSHOT_FORMAT_VERSION: u32 = 24;
pub(super) const LANDLOOK_MAPSTATS_SNAPSHOT_FORMAT_VERSION: u32 = 25;
pub(super) const LAND_LAYOUT_SNAPSHOT_FORMAT_VERSION: u32 = 26;
pub(super) const PLAYER_MAP_CATALOG_SNAPSHOT_FORMAT_VERSION: u32 = 27;
pub(super) const PLAYER_MAP_NAME_CATALOG_SNAPSHOT_FORMAT_VERSION: u32 = 28;
pub(super) const SPECIAL_LAND_SOLIDITY_SNAPSHOT_FORMAT_VERSION: u32 = 29;
pub(super) const PRE_CLASSIC_RESOURCE_REMOVALS_SNAPSHOT_FORMAT_VERSION: u32 = 32;
pub(super) const PRE_SCRIPT_DESCRIPTOR_CATALOG_SNAPSHOT_FORMAT_VERSION: u32 = 33;

pub(super) fn validate(version: u32) -> Result<(), super::SnapshotError> {
    if (LEGACY_SNAPSHOT_FORMAT_VERSION..=crate::model::SNAPSHOT_FORMAT_VERSION).contains(&version) {
        Ok(())
    } else {
        Err(super::SnapshotError::UnsupportedVersion(version))
    }
}
