export const SCENARIO_SEED_NAMED_TILE_NAMES = [
  "open-ground",
  "shoreline-land-west",
  "shoreline-land-east",
  "shoreline-land-north",
  "shoreline-land-south",
  "full-water",
  "water-rocks",
  "single-tile-island",
  "narrow-stream-north-south",
  "narrow-stream-east-west",
  "narrow-stream-to-land-land-south",
  "narrow-stream-to-land-land-west",
  "narrow-stream-to-land-land-north",
  "narrow-stream-to-land-land-east",
  "narrow-stream-trifork-north-west-east",
  "narrow-stream-trifork-north-east-south",
  "narrow-stream-trifork-west-south-east",
  "narrow-stream-trifork-north-west-south",
  "narrow-stream-bend-south-east",
  "narrow-stream-bend-south-west",
  "narrow-stream-bend-north-east",
  "narrow-stream-bend-north-west",
  "stream-to-cave-cave-west",
  "stream-to-cave-cave-east",
  "stream-to-cave-cave-south",
  "stream-to-cave-cave-north",
  "land-to-cave-cave-east",
  "land-to-cave-cave-west",
  "land-to-cave-cave-south",
  "land-to-cave-cave-north",
  "solid-barrier",
  "forest-center",
  "boat",
  "tree-single",
  "tree-pair",
  "tree-cluster",
  "bridge-over-water",
  "grave",
  "hut",
  "connected-huts-two",
  "connected-huts-three",
  "tent",
  "tents-two",
  "castle-wall-north-south",
  "castle-wall-east-west",
  "wall-lever-east",
  "wall-lever-south",
  "wall-torch-east",
  "wall-torch-south",
  "stairs-east-up",
  "stairs-down",
  "pit",
  "acid-pit",
  "lava",
  "acid",
  "shallow-water",
  "portcullis-north-south",
  "portcullis-east-west",
  "wooden-door-north-south",
  "wooden-door-east-west",
  "red-rug-center",
  "floor-hatch",
  "double-wooden-door",
  "wooden-bridge-horizontal",
  "wooden-bridge-vertical",
  "marble-floor",
  "floor-broken-stones",
  "floor-stains",
  "floor-bloodstain",
  "floor-bloodstains",
  "floor-slime",
  "floor-scroll",
  "floor-skull",
  "treasure-pile",
  "machine-lever-up",
  "machine-lever-down",
  "floor-lever-down",
  "floor-lever-up",
  "skeleton-remains",
  "sack",
  "sacks",
  "chair-east",
  "chair-west",
  "stool",
  "weapon-rack-empty",
  "weapon-rack-swords",
  "weapon-rack-spears",
  "weapon-rack-javelins",
  "weapon-rack-axes",
  "ladder-up",
  "ladder-down",
  "supplies",
  "crates",
  "barrels",
  "jugs",
  "colored-rack",
  "stone-column",
  "throne",
  "workbench",
  "alchemy-table",
  "desk-north",
  "desk-south",
  "chest-white",
  "chest-ornate",
  "chest-west",
  "standing-torch",
  "standing-mirror",
  "bookcase-short",
  "bookcase-skull",
  "dresser",
  "dresser-books",
  "statue-green",
  "statue-blue",
  "statue-white",
  "brazier",
  "platform-water",
  "platform-acid",
  "platform-lava",
  "magic-bubble"
] as const;

export type ScenarioSeedNamedTileName = typeof SCENARIO_SEED_NAMED_TILE_NAMES[number];

type NamedTileVariants = Partial<Record<ScenarioSeedNamedTileName, readonly number[]>>;

const ALIGNED_TERRAIN_LANDLOOKS = new Set([0, 2, 3, 5, 9, 10]);

const ALIGNED_TERRAIN_TILES: NamedTileVariants = {
  "shoreline-land-west": [1],
  "shoreline-land-east": [2],
  "shoreline-land-north": [3],
  "shoreline-land-south": [4],
  "full-water": [60],
  "narrow-stream-north-south": [38],
  "narrow-stream-east-west": [39],
  "narrow-stream-to-land-land-south": [40],
  "narrow-stream-to-land-land-west": [41],
  "narrow-stream-to-land-land-north": [42],
  "narrow-stream-to-land-land-east": [43],
  "narrow-stream-trifork-north-west-east": [44],
  "narrow-stream-trifork-north-east-south": [45],
  "narrow-stream-trifork-west-south-east": [46],
  "narrow-stream-trifork-north-west-south": [47],
  "narrow-stream-bend-south-east": [48],
  "narrow-stream-bend-south-west": [49],
  "narrow-stream-bend-north-east": [50],
  "narrow-stream-bend-north-west": [51],
  "stream-to-cave-cave-west": [105],
  "stream-to-cave-cave-east": [106],
  "stream-to-cave-cave-south": [107],
  "stream-to-cave-cave-north": [108],
  "land-to-cave-cave-east": [109],
  "land-to-cave-cave-west": [110],
  "land-to-cave-cave-south": [111],
  "land-to-cave-cave-north": [112],
  "solid-barrier": [61],
  "forest-center": [121],
  "boat": [147],
  "tree-single": [118],
  "tree-pair": [119],
  "tree-cluster": [120]
};

const COMMON_SETTLEMENT_TILES: NamedTileVariants = {
  "hut": [170],
  "connected-huts-two": [175],
  "connected-huts-three": [176],
  "tent": [177],
  "tents-two": [178]
};

const CASTLE_TILES: NamedTileVariants = {
  "open-ground": [111, 155],
  "castle-wall-north-south": [1],
  "castle-wall-east-west": [2],
  "wall-lever-east": [7],
  "wall-lever-south": [8],
  "wall-torch-east": [9],
  "wall-torch-south": [10],
  "stairs-east-up": [58],
  "stairs-down": [69],
  "pit": [68],
  "acid-pit": [70],
  "lava": [71],
  "acid": [72],
  "shallow-water": [73],
  "portcullis-north-south": [74],
  "portcullis-east-west": [75],
  "wooden-door-north-south": [76],
  "wooden-door-east-west": [77],
  "red-rug-center": [78],
  "floor-hatch": [91],
  "double-wooden-door": [92],
  "wooden-bridge-horizontal": [93],
  "wooden-bridge-vertical": [94],
  "marble-floor": [95],
  "floor-broken-stones": [97],
  "floor-stains": [98],
  "floor-bloodstain": [112],
  "floor-bloodstains": [113],
  "floor-slime": [114],
  "floor-scroll": [115],
  "floor-skull": [116],
  "treasure-pile": [117],
  "machine-lever-up": [118],
  "machine-lever-down": [119],
  "floor-lever-down": [121],
  "floor-lever-up": [122],
  "skeleton-remains": [123],
  "sack": [124],
  "sacks": [125],
  "chair-east": [126],
  "chair-west": [127],
  "stool": [128],
  "weapon-rack-empty": [129],
  "weapon-rack-swords": [130],
  "weapon-rack-spears": [131],
  "weapon-rack-javelins": [132],
  "weapon-rack-axes": [133],
  "ladder-up": [134],
  "ladder-down": [135],
  "supplies": [136],
  "crates": [137],
  "barrels": [138],
  "jugs": [139],
  "colored-rack": [140],
  "stone-column": [141],
  "throne": [144],
  "workbench": [145],
  "alchemy-table": [146],
  "desk-north": [147],
  "desk-south": [148],
  "chest-white": [149],
  "chest-ornate": [150],
  "chest-west": [151],
  "standing-torch": [152],
  "standing-mirror": [167],
  "bookcase-short": [169],
  "bookcase-skull": [170],
  "dresser": [171],
  "dresser-books": [172],
  "statue-green": [173],
  "statue-blue": [174],
  "statue-white": [175],
  "brazier": [176],
  "platform-water": [181],
  "platform-acid": [182],
  "platform-lava": [183],
  "magic-bubble": [184]
};

const LANDLOOK_TILES: Record<number, NamedTileVariants> = {
  0: { "open-ground": [156], "water-rocks": [33, 34, 35], "single-tile-island": [56, 57, 58, 59], "grave": [52, 53, 54] },
  2: { "open-ground": [156], "water-rocks": [33, 34, 35], "single-tile-island": [56, 57, 58, 59], "grave": [52, 53, 54] },
  3: { "open-ground": [156], "water-rocks": [33, 34, 35], "single-tile-island": [56, 57, 58, 59], "grave": [52, 53, 54] },
  4: CASTLE_TILES,
  5: { "open-ground": [191, 192], "bridge-over-water": [115, 130], ...COMMON_SETTLEMENT_TILES },
  9: { "open-ground": [155, 156, 157, 158], "grave": [187, 188, 189], ...COMMON_SETTLEMENT_TILES },
  10: { "open-ground": [155, 156, 157, 158, 159, 160], "bridge-over-water": [115], "grave": [187, 188, 189], ...COMMON_SETTLEMENT_TILES }
};

const NAMED_TILE_NAME_SET = new Set<string>(SCENARIO_SEED_NAMED_TILE_NAMES);

export function isScenarioSeedNamedTileName(value: string): value is ScenarioSeedNamedTileName {
  return NAMED_TILE_NAME_SET.has(value);
}

export function namedLandTileVariants(landlook: number, name: ScenarioSeedNamedTileName): readonly number[] {
  const exact = LANDLOOK_TILES[landlook]?.[name];
  if (exact?.length) return exact;
  return ALIGNED_TERRAIN_LANDLOOKS.has(landlook) ? ALIGNED_TERRAIN_TILES[name] ?? [] : [];
}

export function resolveNamedLandTile(landlook: number, name: ScenarioSeedNamedTileName, variant = 1): number | null {
  const variants = namedLandTileVariants(landlook, name);
  if (!Number.isInteger(variant) || variant < 1 || variant > variants.length) return null;
  return variants[variant - 1] ?? null;
}
