import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const policyPath = path.join(root, "schemas", "realmz-native-manifest-policy.json");
const typescriptPath = path.join(root, "src", "editor", "generated", "realmzNativeManifestPolicy.ts");
const rustPath = path.join(root, "src-tauri", "src", "generated", "native_manifest_policy.rs");
const browserBaselinePath = path.join(root, "src", "editor", "browser", "scenarioCompilerBaseline.ts");
const rustExporterPath = path.join(root, "src-tauri", "src", "exporter.rs");
const checkOnly = process.argv.includes("--check");

const policy = JSON.parse(fs.readFileSync(policyPath, "utf8"));
const baseline = policy.authoredBaseline;

expect(Number.isInteger(policy.contractVersion) && policy.contractVersion > 0, "contractVersion must be a positive integer");
expect(baseline && typeof baseline === "object" && !Array.isArray(baseline), "authoredBaseline must be an object");
expect(Number.isInteger(baseline.scenarioItemRecords) && baseline.scenarioItemRecords > 0, "scenarioItemRecords must be a positive integer");
expect(Array.isArray(baseline.emptyRuntimeFiles) && baseline.emptyRuntimeFiles.length > 0, "emptyRuntimeFiles must be a non-empty array");
expect(new Set(baseline.emptyRuntimeFiles).size === baseline.emptyRuntimeFiles.length, "emptyRuntimeFiles must not contain duplicates");
for (const fileName of baseline.emptyRuntimeFiles) {
  expect(typeof fileName === "string" && fileName.trim() === fileName && fileName.length > 0, "emptyRuntimeFiles entries must be non-empty trimmed strings");
  expect(!fileName.includes("/") && !fileName.includes("\\"), `emptyRuntimeFiles entry ${JSON.stringify(fileName)} must be a top-level native filename`);
}
expect(!baseline.emptyRuntimeFiles.includes("Data DDD"), "Data DDD is conditionally generated from dungeon levels and must not be classified as always empty");

const typescript = `// Generated by scripts/generate_realmz_native_manifest_policy.mjs; do not edit.\n\nexport const AUTHORED_SCENARIO_ITEM_RECORDS = ${baseline.scenarioItemRecords} as const;\n\nexport const AUTHORED_EMPTY_RUNTIME_FILES = ${JSON.stringify(baseline.emptyRuntimeFiles, null, 2)} as const;\n`;
const rustFiles = baseline.emptyRuntimeFiles.map((fileName) => `    ${JSON.stringify(fileName)},`).join("\n");
const rust = `// Generated by scripts/generate_realmz_native_manifest_policy.mjs; do not edit.\n\npub const AUTHORED_SCENARIO_ITEM_RECORDS: usize = ${baseline.scenarioItemRecords};\n\n#[rustfmt::skip]\npub const AUTHORED_EMPTY_RUNTIME_FILES: &[&str] = &[\n${rustFiles}\n];\n`;

writeOrCheck(typescriptPath, typescript);
writeOrCheck(rustPath, rust);

const browserBaselineSource = fs.readFileSync(browserBaselinePath, "utf8");
const rustExporterSource = fs.readFileSync(rustExporterPath, "utf8");
for (const symbol of ["AUTHORED_SCENARIO_ITEM_RECORDS", "AUTHORED_EMPTY_RUNTIME_FILES"]) {
  expect(browserBaselineSource.includes(symbol), `browser scenario baseline must consume ${symbol}`);
  expect(rustExporterSource.includes(symbol), `Rust scenario baseline must consume ${symbol}`);
}
expect(!browserBaselineSource.includes("const EMPTY_RUNTIME_TABLES"), "browser scenario baseline must not redeclare empty runtime policy");
expect(!rustExporterSource.includes("const EMPTY_RUNTIME_TABLES"), "Rust scenario baseline must not redeclare empty runtime policy");

console.log(`${checkOnly ? "Realmz native manifest policy is current" : "Generated Realmz native manifest policy"} (contract v${policy.contractVersion}, ${baseline.emptyRuntimeFiles.length} empty runtime files).`);

function writeOrCheck(filePath, content) {
  if (checkOnly) {
    const current = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : null;
    expect(current === content, `${path.relative(root, filePath)} is stale; run npm run generate:realmz-native-manifest-policy`);
    return;
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
}

function expect(condition, message) {
  if (!condition) throw new Error(message);
}
