import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const catalogPath = resolve(root, "schemas/remake-scenario-capabilities.v2.json");
const outputPath = resolve(root, "docs/generated/scenario-api-v2.md");
const check = process.argv.includes("--check");
const catalog = JSON.parse(await readFile(catalogPath, "utf8"));
const failures = [];

for (const role of catalog.roles ?? []) {
  for (const field of ["id", "label", "contextType", "resultType", "summary", "reference", "example"]) {
    if (!String(role[field] ?? "").trim()) failures.push(`Role ${role.id ?? "?"} lacks ${field}`);
  }
  if (!Array.isArray(role.hooks)) failures.push(`Role ${role.id ?? "?"} lacks hooks`);
  if (!Array.isArray(role.runtimeHooks)) failures.push(`Role ${role.id ?? "?"} lacks runtimeHooks`);
}
for (const operation of catalog.operations ?? []) {
  for (const field of ["id", "label", "category", "owningPort", "minimumTier", "result", "summary", "reference", "example"]) {
    if (!String(operation[field] ?? "").trim()) failures.push(`Operation ${operation.id ?? "?"} lacks ${field}`);
  }
  if (!Array.isArray(operation.roles) || operation.roles.length === 0) {
    failures.push(`Operation ${operation.id ?? "?"} lacks compatible roles`);
  }
  if (!operation.parameters || typeof operation.parameters !== "object" || Array.isArray(operation.parameters)) {
    failures.push(`Operation ${operation.id ?? "?"} lacks a parameter contract`);
  }
}
if (failures.length) {
  throw new Error(`Scenario API catalog documentation is incomplete:\n- ${failures.join("\n- ")}`);
}

const lines = [
  "# Scenario API v2",
  "",
  "> Generated from `schemas/remake-scenario-capabilities.v2.json`. Do not edit this file by hand.",
  "",
  `API version: **${catalog.apiVersion}**`,
  `Execution budget: **${catalog.executionBudget.toLocaleString()} Safe instructions**`,
  "",
  "## Behavior roles",
  ""
];
for (const role of catalog.roles) {
  const runtimeHooks = role.runtimeHooks ?? role.hooks;
  const plannedHooks = role.hooks.filter((hook) => !runtimeHooks.includes(hook));
  lines.push(
    `### ${role.label}`,
    "",
    role.summary,
    "",
    `- Stable ID: \`${role.id}\``,
    `- Context: \`${role.contextType}\``,
    `- Result: \`${role.resultType}\``,
    `- Runtime hooks: ${runtimeHooks.length ? runtimeHooks.map((hook) => `\`${hook}\``).join(", ") : "none"}`,
    ...(plannedHooks.length
      ? [`- Reserved hooks not yet connected: ${plannedHooks.map((hook) => `\`${hook}\``).join(", ")}`]
      : []),
    `- May yield: ${role.allowsYield ? "yes" : "no"}`,
    "",
    role.reference,
    "",
    "```gdscript",
    role.example,
    "```",
    ""
  );
}
lines.push("## Operations", "");
const categories = new Map();
for (const operation of catalog.operations) {
  const list = categories.get(operation.category) ?? [];
  list.push(operation);
  categories.set(operation.category, list);
}
for (const [category, operations] of categories) {
  lines.push(`### ${category}`, "");
  for (const operation of operations) {
    const parameters = Object.entries(operation.parameters)
      .map(([name, type]) => `\`${name}: ${type}\``)
      .join(", ");
    lines.push(
      `#### ${operation.label}`,
      "",
      operation.summary,
      "",
      `- Stable ID: \`${operation.id}\``,
      `- Port: \`${operation.owningPort}\``,
      `- Parameters: ${parameters || "none"}`,
      `- Result: \`${operation.result}\``,
      `- Roles: ${operation.roles.map((role) => `\`${role}\``).join(", ")}`,
      `- Behavior: ${operation.yields ? "yielding" : "immediate"}; ${operation.mutates ? "mutates validated state" : "query/presentation only"}`,
      "",
      operation.reference,
      "",
      "```gdscript",
      operation.example,
      "```",
      ""
    );
  }
}
const output = `${lines.join("\n").trim()}\n`;
if (check) {
  const existing = await readFile(outputPath, "utf8").catch(() => "");
  if (existing !== output) throw new Error("Generated Scenario API reference is stale");
} else {
  await writeFile(outputPath, output);
  console.log(`Generated ${outputPath}`);
}
