import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const localCatalogPath = path.join(root, "schemas", "remake-extension-catalog.json");
const outputPath = path.join(root, "src", "editor", "generated", "remakeExtensionCatalog.ts");
const checkOnly = process.argv.includes("--check");
const remakeRootIndex = process.argv.indexOf("--remake-root");
const remakeRoot = remakeRootIndex >= 0 ? process.argv[remakeRootIndex + 1] : null;
if (remakeRootIndex >= 0 && !remakeRoot) {
  throw new Error("--remake-root requires the Realmz Remake checkout path");
}
const sourcePath = remakeRoot
  ? path.join(path.resolve(remakeRoot), "src", "scripts", "scenario_runtime", "extensions", "catalog.json")
  : localCatalogPath;

const sourceText = await fs.readFile(sourcePath, "utf8");
const catalog = JSON.parse(sourceText);
validateCatalog(catalog);
const canonicalCatalogText = `${JSON.stringify(catalog, null, 2)}\n`;
const generated = `// Generated by scripts/generate_remake_extension_catalog.mjs. Do not edit by hand.
export const REMAKE_EXTENSION_CATALOG = ${JSON.stringify(catalog, null, 2)} as const;

export type RemakeExtensionCatalog = typeof REMAKE_EXTENSION_CATALOG;
export type RemakeExtensionDescriptor = RemakeExtensionCatalog["extensions"][number];
`;

if (checkOnly) {
  if (remakeRoot) {
    const localText = await fs.readFile(localCatalogPath, "utf8");
    if (`${JSON.stringify(JSON.parse(localText), null, 2)}\n` !== canonicalCatalogText) {
      throw new Error(`Providence extension catalog is out of sync with ${sourcePath}`);
    }
  }
  const current = await fs.readFile(outputPath, "utf8").catch(() => "");
  if (current !== generated) {
    throw new Error("Generated Remake extension catalog is stale; run npm run generate:remake-extension-catalog");
  }
  console.log(`Verified ${catalog.extensions.length} Remake extension descriptor(s).`);
  process.exit(0);
}

if (remakeRoot) {
  await fs.writeFile(localCatalogPath, canonicalCatalogText);
}
await fs.mkdir(path.dirname(outputPath), { recursive: true });
await fs.writeFile(outputPath, generated);
console.log(`Generated ${catalog.extensions.length} Remake extension descriptor(s) from ${sourcePath}.`);

function validateCatalog(value) {
  if (!value || value.schemaVersion !== 1 || !Array.isArray(value.extensions)) {
    throw new Error("Remake extension catalog must use schemaVersion 1 and contain extensions");
  }
  const extensionIds = new Set();
  const bindingIds = new Set();
  for (const extension of value.extensions) {
    requireNamespaced(extension.id, "extension ID");
    if (extension.id.startsWith("core.")) throw new Error(`Extension ${extension.id} uses the reserved core namespace`);
    if (extensionIds.has(extension.id)) throw new Error(`Duplicate extension ID ${extension.id}`);
    extensionIds.add(extension.id);
    if (!Number.isInteger(extension.apiVersion) || extension.apiVersion < 1) {
      throw new Error(`Extension ${extension.id} requires a positive apiVersion`);
    }
    if (!extension.configurationSchema || extension.configurationSchema.type !== "object") {
      throw new Error(`Extension ${extension.id} requires an object configurationSchema`);
    }
    const capabilities = extension.capabilities ?? {};
    for (const [capability, entries] of Object.entries(capabilities)) {
      if (!Array.isArray(entries)) throw new Error(`${extension.id}.${capability} must be an array`);
      for (const entry of entries) {
        const id = typeof entry === "string" ? entry : entry?.id;
        requireNamespaced(id, `${extension.id}.${capability} binding`);
        if (id.startsWith("core.")) throw new Error(`Binding ${id} uses the reserved core namespace`);
        const key = `${capability}:${id}`;
        if (bindingIds.has(key)) throw new Error(`Duplicate ${capability} binding ${id}`);
        bindingIds.add(key);
        if (capability === "semanticOperations" && (typeof entry !== "object" || entry.parametersSchema?.type !== "object")) {
          throw new Error(`Semantic operation ${id} requires an object parametersSchema`);
        }
      }
    }
  }
}

function requireNamespaced(value, label) {
  if (typeof value !== "string" || !/^[a-z0-9][a-z0-9-]*(\.[a-z0-9][a-z0-9-]*)+$/.test(value)) {
    throw new Error(`${label} must be a stable namespaced identifier`);
  }
}
